runConfig = [
    // deposit
    {
        'data':[
        {
            'type':'deposit',
            // 'times':100,
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':6,
                },
                {
                    'tokenAddress':2,
                    'accountAddress':1,
                    'amount':12,
                },
                {
                    'tokenAddress':3,
                    'accountAddress':1,
                    'amount':18,
                },
                {
                    'tokenAddress':4,
                    'accountAddress':1,
                    'amount':24,
                },
            ]
        },
        {
            'type':'updateSection'
        },
        {
            'type':'deposit',
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':7,
                },
                {
                    'tokenAddress':2,
                    'accountAddress':1,
                    'amount':14,
                },
                {
                    'tokenAddress':3,
                    'accountAddress':1,
                    'amount':21,
                },
                {
                    'tokenAddress':4,
                    'accountAddress':1,
                    'amount':28,
                },
            ]
        },
        {
            'type':'updateSection'
        },
        {
            'type':'deposit',
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':8,
                },
                {
                    'tokenAddress':2,
                    'accountAddress':1,
                    'amount':16,
                },
                {
                    'tokenAddress':3,
                    'accountAddress':1,
                    'amount':24,
                },
                {
                    'tokenAddress':4,
                    'accountAddress':1,
                    'amount':32,
                },
            ]
        }
    ],
    },

    // destroy
    {
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':10,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':60,
                    }
                ]
            },
        ],
    },

    {
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':61,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':130,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':131,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':210,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':10,
                    },
                    {
                        'accountAddress':1,
                        'amount':10,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':10,
                    },
                    {
                        'accountAddress':1,
                        'amount':50,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':10,
                    },
                    {
                        'accountAddress':1,
                        'amount':51,
                    }
                ]
            },
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':6,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':12,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':18,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':24,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':7,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':14,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':21,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':28,
                    },
                ]
            },
            {
                'type':'updateSection'
            },
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':8,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':1,
                        'amount':16,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':1,
                        'amount':24,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':1,
                        'amount':32,
                    },
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':61,
                    },
                    {
                        'accountAddress':1,
                        'amount':71,
                    }
                ]
            },
        ],
    },

    // withdraw    
    {    
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':1,
                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    },
                    {
                        'tokenAddress':1,
                        'accountAddress':2,
                        'amount':100,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':49,
                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    },
                    {
                        'tokenAddress':1,
                        'accountAddress':2,
                        'amount':100,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':50,
                    },
                    {
                        'tokenAddress':1,
                        'accountAddress':2,
                        'amount':100,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':2,
                        'amount':49,
                    },
                    {
                        'tokenAddress':1,
                        'accountAddress':2,
                        'amount':50,
                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'times': 300,
                'data':[
                    {
                        'tokenAddress':1
                    },
                    {
                        'tokenAddress':2
                    },
                    {
                        'tokenAddress':3
                    }
                ]
            },
            {
                'type':'withdraw',
                'times':20,
                'data':[
                    {
                        'tokenAddress':1,
                        'amount':49,
                    },
                    {
                        'tokenAddress':1,
                    },
                    {
                        'tokenAddress':2,
                        'total':true
                    },
                    {
                        'tokenAddress':3,
                        'total':true
                    },
                    {

                    }
                ]
            }
        ],
    },

    {    
        'data':[
            {
                'type':'deposit',
                'times': 300,
                'data':[
                    {
                        'tokenAddress':1
                    },
                    {
                        'tokenAddress':2
                    },
                    {
                        'tokenAddress':3
                    }
                ]
            },
            {
                'type':'withdraw',
                'times':20,
                'data':[
                    {
                        'tokenAddress':1,
                        'amount':49,
                    },
                    {
                        'tokenAddress':1,
                    },
                    {
                        'tokenAddress':2,
                        'total':true
                    },
                    {
                        'tokenAddress':3,
                        'total':true
                    },
                    {

                    }
                ]
            }
        ],
    }
];
   