var runConfig = [
    // deposit
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                }
            ],
    // destroy
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':10,
                        }
                    ]
                },
            ],
    
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':60,
                        }
                    ]
                },
            ],
            
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':61,
                        }
                    ]
                },
            ],
    
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':130,
                        }
                    ]
                },
            ],
    
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':131,
                        }
                    ]
                },
            ],
            
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':210,
                        }
                    ]
                },
            ],
        
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':10,
                        },
                        {
                            'accountAddress':1,
                            'amount':10,
                        }
                    ]
                },
            ],
        
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':10,
                        },
                        {
                            'accountAddress':1,
                            'amount':50,
                        }
                    ]
                },
            ],
        
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':10,
                        },
                        {
                            'accountAddress':1,
                            'amount':51,
                        }
                    ]
                },
            ],
        
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':6,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':12,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':18,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':24,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':7,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':14,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':21,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':28,
                        },
                    ]
                },
                {
                    'type':'updateSection'
                },
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':8,
                        },
                        {
                            'tokenAddress':2,
                            'accountAddress':1,
                            'amount':16,
                        },
                        {
                            'tokenAddress':3,
                            'accountAddress':1,
                            'amount':24,
                        },
                        {
                            'tokenAddress':4,
                            'accountAddress':1,
                            'amount':32,
                        },
                    ]
                },
                {
                    'type':'destroy',
                    'data':[
                        {
                            'accountAddress':1,
                            'amount':61,
                        },
                        {
                            'accountAddress':1,
                            'amount':71,
                        }
                    ]
                },
            ],
    // withdraw    
            [
                {
                    'type':'deposit',
                    // 'times':100,
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':1,
                        }
                    ]
                }
            ],
    
            [
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        }
                    ]
                }
            ],
    
            [
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        },
                        {
                            'tokenAddress':1,
                            'accountAddress':2,
                            'amount':100,
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':49,
                        }
                    ]
                }
            ],
    
            [
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        },
                        {
                            'tokenAddress':1,
                            'accountAddress':2,
                            'amount':100,
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        }
                    ]
                }
            ],
        
            [
                {
                    'type':'deposit',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':1,
                            'amount':50,
                        },
                        {
                            'tokenAddress':1,
                            'accountAddress':2,
                            'amount':100,
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'data':[
                        {
                            'tokenAddress':1,
                            'accountAddress':2,
                            'amount':49,
                        },
                        {
                            'tokenAddress':1,
                            'accountAddress':2,
                            'amount':50,
                        }
                    ]
                }
            ],
        
            [
                {
                    'type':'deposit',
                    'times': 300,
                    'data':[
                        {
                            'tokenAddress':1
                        },
                        {
                            'tokenAddress':2
                        },
                        {
                            'tokenAddress':3
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'times':20,
                    'data':[
                        {
                            'tokenAddress':1,
                            'amount':49,
                        },
                        {
                            'tokenAddress':1,
                        },
                        {
                            'tokenAddress':2,
                            'total':true
                        },
                        {
                            'tokenAddress':3,
                            'total':true
                        },
                        {
    
                        }
                    ]
                }
            ],
        
            [
                {
                    'type':'deposit',
                    'times': 300,
                    'data':[
                        {
                            'tokenAddress':1
                        },
                        {
                            'tokenAddress':2
                        },
                        {
                            'tokenAddress':3
                        }
                    ]
                },
                {
                    'type':'withdraw',
                    'times':20,
                    'data':[
                        {
                            'tokenAddress':1,
                            'amount':49,
                        },
                        {
                            'tokenAddress':1,
                        },
                        {
                            'tokenAddress':2,
                            'total':true
                        },
                        {
                            'tokenAddress':3,
                            'total':true
                        },
                        {
    
                        }
                    ]
                }
            ],
        
        ];
   