// type:'deposit', 'destroy', 'withdraw', 'updateSection', 'claim'
// tokenAddress 1~4
// accountAddress 1~20
// total true: all false: invalid parameter
// times The number of executions. If there is no such parameter, it will be executed once according to the data configuration type.
// data Specific implementation, if you need to insert random mode, add {}
// If the configuration is not filled in, the measurement is performed in random mode.
// ------------------------run test case
// The terminal starts the ETH node.
// ganache-cli --port=7545 --gasLimit=8000000 --accounts=10 --defaultBalanceEther=10000
// Compile contract
// npm run build
// Run command
// truffle test .\test\test0.3.js > test0.3.log
collateralNames = new Array('DAI', 'PAX', 'TUSD', 'USDC');
weightTest = new Array(0.1, 0.3, 0.3, 0.3);
runConfig = [ 
//deposit-convert-section[1]-deposit-withdraw3-destroy2-claim-deposit-claim-withdraw6-destroy3
// X（USDx:0.8）
// Y（USDx:4.2）
// Z（USDx:2.4）
// Q（USDx:2.4）
// W（USDx:0.6）            
    {
        'data':[
        {
            'type':'deposit',
            // 'times':100,
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':1.2,
                },
                {
                    'tokenAddress':2,
                    'accountAddress':2,
                    'amount':2.4,
                },
                {
                    'tokenAddress':3,
                    'accountAddress':3,
                    'amount':3.6,
                },
                {
                    'tokenAddress':4,
                    'accountAddress':4,
                    'amount':4.8,
                },
            ]
        },
    //section[1]                
        {
            'type':'updateSection',
            // 'times':100,
            'data':[
                {
                    'tokens':[1, 2],
                    'weight':[1, 3],
                },
            ]
        },                
        {
            'type':'deposit',
            // 'times':100,
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':5,
                    'amount':0.6,
                }
            ]
        },
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':3,
                    'accountAddress':3,
                    'amount':1.3,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':3,
                    'accountAddress':3,
                    'amount':0.01,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':3,
                    'accountAddress':3,
                    'amount':1.19,
                }
            ]
        }, 
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':1,
                    'amount':0.1,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':2,
                    'amount':0.1,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':3,
                    'amount':0.1,
                }
            ]
        },
        {
            'type':'claim',
            'data':[
                {
                'accountAddress':1   //提取0.2 USDx
                },
                {
                'accountAddress':2   //提取2.4 USDx
                },
                {
                'accountAddress':3   //提取2.4 USDx
                },
                {
                'accountAddress':4   //return 空或0
                },
                {
                'accountAddress':5   //return 空或0
                },
            ]
        },
        {
            'type':'deposit',
            // 'times':100,
            'data':[
                {
                    'tokenAddress':2,
                    'accountAddress':2,
                    'amount':1.9,
                }
            ]
        },               
        {
            'type':'claim',
            'data':[
                {
                'accountAddress':1   //提取0.6 USDx
                },
                {
                'accountAddress':2   //return 空或0
                },
            ]
        },
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':0.5,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':0.1,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':1,
                    'accountAddress':1,
                    'amount':0.4,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':2,
                    'accountAddress':2,
                    'amount':0.11,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':2,
                    'accountAddress':2,
                    'amount':0.01,
                }
            ]
        }, 
        {
            'type':'withdraw',
            'data':[
                {
                    'tokenAddress':2,
                    'accountAddress':2,
                    'amount':0.09,
                }
            ]
        }, 
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':1,
                    'amount':0.81,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':1,
                    'amount':0.01,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':1,
                    'amount':0.79,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':2,
                    'amount':4.3,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':2,
                    'amount':0.01,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':2,
                    'amount':4.19,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':3,
                    'amount':2.41,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':3,
                    'amount':0.01,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':3,
                    'amount':2.39,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':4,
                    'amount':2.41,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':4,
                    'amount':0.01,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':4,
                    'amount':2.39,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':5,
                    'amount':0.61,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':5,
                    'amount':0.01,
                }
            ]
        },
        {
            'type':'destroy',
            'data':[
                {
                    'accountAddress':5,
                    'amount':0.59,
                }
            ]
        },
    ],          
    },
//dection[0]-deposit-convert-section[1]-deposit(no convert)-withdraw3-destroy2-claim-deposit(convert)-claim-section[2]-deposit-convert-withdraw6-claim-destroy3
// X（USDx:1.8）
// Y（USDx:6.7）
// Z（USDx:4.8）
// Q（USDx:2.4）
// W（USDx:0.6）            
    {
        'data':[
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':1.2,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':2,
                        'amount':2.4,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':3.6,
                    },
                    {
                        'tokenAddress':4,
                        'accountAddress':4,
                        'amount':4.8,
                    },
                ]
            },
        //section[1]                
            {
                'type':'updateSection',
                // 'times':100,
                'data':[
                    {
                        'tokens':[1, 2],
                        'weight':[1, 3],
                    },
                ]
            },                
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':5,
                        'amount':0.6,
                    }
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':1.3,
                    }
                ]
            }, 
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':0.01,
                    }
                ]
            }, 
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':1.19,
                    }
                ]
            }, 
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':0.1,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':2,
                        'amount':0.1,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':3,
                        'amount':0.1,
                    }
                ]
            },
            {
                'type':'claim',
                'data':[
                    {
                    'accountAddress':1   //提取0.2 USDx
                    },
                    {
                    'accountAddress':2   //提取2.4 USDx
                    },
                    {
                    'accountAddress':3   //提取2.4 USDx
                    },
                    {
                    'accountAddress':4   //return 空或0
                    },
                    {
                    'accountAddress':5   //return 空或0
                    },
                ]
            },
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':2,
                        'accountAddress':2,
                        'amount':1.9,
                    }
                ]
            },               
            {
                'type':'claim',
                'data':[
                    {
                    'accountAddress':1   //提取0.6 USDx
                    },
                    {
                    'accountAddress':2   //return 空或0
                    },
                ]
            },
            //section[2]                
            {
                'type':'updateSection',
                // 'times':100,
                'data':[
                    {
                        'tokens':[1, 2, 3],
                        'weight':[0.1, 0.3, 0.3],
                    },
                ]
            }, 
            {
                'type':'deposit',
                // 'times':100,
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':1.2,
                    },
                    {
                        'tokenAddress':2,
                        'accountAddress':2,
                        'amount':2.4,
                    },
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':3.6,
                    },
                ]
            },
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':0.1,
                    }
                ]
            }, 
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':1,
                        'accountAddress':1,
                        'amount':0.7,
                    }
                ]
            }, 
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':0.01,
                    }
                ]
            }, 
            {
                'type':'withdraw',
                'data':[
                    {
                        'tokenAddress':3,
                        'accountAddress':3,
                        'amount':0.19,
                    }
                ]
            }, 
            {
                'type':'claim',
                'data':[
                    {
                    'accountAddress':1   //提取0.8 USDx
                    },
                    {
                    'accountAddress':2   //提取2.5 USDx
                    },
                ]
            },               
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':1.81,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':0.01,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':1,
                        'amount':1.79,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':2,
                        'amount':6.8,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':2,
                        'amount':0.01,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':2,
                        'amount':6.69,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':3,
                        'amount':4.81,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':3,
                        'amount':0.01,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':3,
                        'amount':4.79,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':4,
                        'amount':2.41,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':4,
                        'amount':0.01,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':4,
                        'amount':2.39,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':5,
                        'amount':0.61,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':5,
                        'amount':0.01,
                    }
                ]
            },
            {
                'type':'destroy',
                'data':[
                    {
                        'accountAddress':5,
                        'amount':0.59,
                    }
                ]
            },
        ],          
    }
];

require('./DFEngine.js');